version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=/api
    container_name: todo-frontend-dev
    stdin_open: true
    tty: true
    
  debug-helper:
    image: busybox
    container_name: debug-helper
