version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: noteapp
      POSTGRES_USER: noteuser
      POSTGRES_PASSWORD: notepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/noteapp
      SPRING_DATASOURCE_USERNAME: noteuser
      SPRING_DATASOURCE_PASSWORD: notepass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    restart: unless-stopped

  # Frontend Service (built and served by Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # No ports exposed as it will be served through Nginx

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
