version: '3.8'

services:
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./todo-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=/api  # Will be proxied by Vite
    container_name: todo-frontend-dev
    stdin_open: true
    tty: true
    networks:
      - todo-network
    depends_on:
      - backend

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./todo-backend:/app
      - /app/node_modules
    networks:
      - todo-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=the_username
      - MONGO_INITDB_ROOT_PASSWORD=the_password
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - mongodb_data:/data/db
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - todo-network

  redis:
    image: redis:6.2
    ports:
      - "26379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todo-network

  debug-helper:
    image: busybox
    container_name: debug-helper
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
